controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_platform:
    resource: .
    type: api_platform

api_login_check:
    path: /api/login_check